version: '2.23.0'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.dockerfile
    volumes:
      - mysql_volume:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_USERNAME
      - MYSQL_ROOT_PASSWORD
    networks:
      app-network:
        ipv4_address: 172.20.1.3

  tuktuk:
    build:
      context: .
      dockerfile: tuktuk.dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    container_name: tuktuk-server
    depends_on:
      - mysql
    environment:
      - DATABASE_URL
      - MYSQL_ROOT_USERNAME
      - MYSQL_ROOT_PASSWORD
    networks:
      app-network:
        ipv4_address: 172.20.1.2
    restart: always

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24

volumes:
  mysql_volume: